#!/bin/bash
sudo yum install httpd -y
service httpd start
chkconfig httpd on
mkdir /var/www/html/register
echo "<html> <h1> Accounts Page </h1></html>">/var/wwww/html/register/index.html



#Installing git and Node Js
sudo yum install git
sudo yum install nodejs
